FROM php:8.0-apache

# Install PDO extension and PDO MySQL driver
RUN docker-php-ext-install pdo pdo_mysql

# Install mysqli extension
RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli
RUN a2enmod rewrite

# Update packages
RUN apt-get update && apt-get upgrade -y

# Set the working directory
WORKDIR /var/www/html

# Copy PHP application files
COPY . /var/www/html

# Expose the PHP application port
EXPOSE 80

# Start Apache server
CMD ["apache2-foreground"]
